services:
  infra-iac:
    build:
      context: .
      dockerfile: infra/Dockerfile
    container_name: datatalent-infra-iac
    working_dir: /workspace/infra
    env_file:
      - .env
    environment:
      GOOGLE_APPLICATION_CREDENTIALS: /root/.config/gcloud/application_default_credentials.json
      TF_VAR_project_id: ${TF_VAR_project_id:-}
      TF_VAR_region: ${TF_VAR_region:-}
      TF_VAR_location: ${TF_VAR_location:-}
      TF_VAR_environment: ${TF_VAR_environment:-dev}
      TF_VAR_project_prefix: ${TF_VAR_project_prefix:-datatalent}
      TF_VAR_bucket_versioning_enabled: ${TF_VAR_bucket_versioning_enabled:-true}
      TF_VAR_bucket_force_destroy: ${TF_VAR_bucket_force_destroy:-false}
      TF_VAR_bucket_lifecycle_delete_age_days: ${TF_VAR_bucket_lifecycle_delete_age_days:-365}
      TF_VAR_raw_dataset_id: ${TF_VAR_raw_dataset_id:-raw}
      TF_VAR_staging_dataset_id: ${TF_VAR_staging_dataset_id:-staging}
      TF_VAR_marts_dataset_id: ${TF_VAR_marts_dataset_id:-marts}
      TF_VAR_ingestion_service_account_email: ${TF_VAR_ingestion_service_account_email:-}
      TF_VAR_dbt_service_account_email: ${TF_VAR_dbt_service_account_email:-}
      TF_VAR_dashboard_service_account_email: ${TF_VAR_dashboard_service_account_email:-}
    volumes:
      - ./:/workspace
      - ./.gcloud:/root/.config/gcloud
    command: ["terraform", "version"]
