name: datatalent_transformation
version: 1.0.0
config-version: 2

profile: datatalent

model-paths: ["models"]
analysis-paths: ["analyses"]
test-paths: ["tests"]
seed-paths: ["seeds"]
macro-paths: ["macros"]
snapshot-paths: ["snapshots"]

target-path: "target"
clean-targets:
  - "target"
  - "dbt_packages"

models:
  datatalent_transformation:
    +persist_docs:
      relation: true
      columns: true

    staging:
      +materialized: view
      +schema: staging

    intermediate:
      +materialized: table
      +schema: staging

    marts:
      +materialized: table
      +schema: marts

seeds:
  datatalent_transformation:
    +schema: raw
